### ISSUE TITLE
Clicking back while audio is playing throws exception

### ISSUE THREAD

**Issue by Nash0x7E2** [juntofoundation/junto-mobile#621]
Clicking the back button while audio is playing throws the following error:

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:251:24)
#1      AudioPlayer._doHandlePlatformCall (package:audioplayers/audioplayers.dart:575:36)
#2      AudioPlayer.platformCallHandler (package:audioplayers/audioplayers.dart:538:7)
#3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
#4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#10     _invoke3 (dart:ui/hooks.dart:289:10)
#11     _dispatchPlatformMessage (d<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:251:24)
#1      AudioPlayer._doHandlePlatformCall (package:audioplayers/audioplayers.dart:586:40)
#2      AudioPlayer.platformCallHandler (package:audioplayers/audioplayers.dart:538:7)
#3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
#4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#10     _invoke3 (dart:ui/hooks.dart:289:10)
#11     _dispatchPlatformMessage (d<…>

```

**Comment by orestesgaolin** [comment]
The reason for that is very strange https://github.com/luanpotter/audioplayers/issues/415
