### ISSUE TITLE
Login crash 

### ISSUE THREAD

**Issue by Nash0x7E2** [juntofoundation/junto-mobile#669]
- Occurs when the user logs out then tries signing back in
- cc: @orestesgaolin I am noticing this on the latest dev, could it be related to #653 ?
```
flutter: Converting object to an encodable object failed: Instance of 'UserData'
flutter: #0      _JsonStringifier.writeObject (dart:convert/json.dart:659:7)
flutter: #1      _JsonStringStringifier.printOn (dart:convert/json.dart:846:17)
flutter: #2      _JsonStringStringifier.stringify (dart:convert/json.dart:831:5)
flutter: #3      JsonEncoder.convert (dart:convert/json.dart:260:30)
flutter: #4      JsonCodec.encode (dart:convert/json.dart:168:45)
flutter: #5      jsonEncode (dart:convert/json.dart:82:10)
flutter: #6      AuthenticationServiceCentralized.loginUser (package:junto_beta_mobile/backend/services/auth_service.dart:38:41)
flutter: <asynchronous suspension>
flutter: #7      AuthRepo.loginUser (package:junto_beta_mobile/backend/repositories/auth_repo.dart:72:48)
flutter: #8      _SignInState._handleSignIn (package:junto_beta_mobile/screens/welcome/sign_in.dart:71:12)
flutter: <asynchronous suspension>
flutter: #9      _SignInState.build.<anonymous closure> (package:junto_beta_mobile/screens/welcome/sign_in.dart:150:21)
flutter: #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
flutter: #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
flutter: #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
flutter: #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
flutter: #15     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
flutter: #16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
flutter: #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
flutter: #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #22     _rootRunUnary (dart:async/zone.dart:1196:13)
flutter: #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
flutter: #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
flutter: #25     _invoke1 (dart:ui/hooks.dart:275:10)
flutter: #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
flutter:
flutter: [ERROR] [PrintLogger.logException]: Caught error: Converting object to an encodable object failed: Instance of 'UserData'
flutter: [DEBUG] [PrintLogger.logException]: In dev mode. Not sending report to Sentry.io.
flutter: [DEBUG] [_RouteEntry.handlePush]: push null from /

```

**Comment by orestesgaolin** [comment]
Yup, I'm on it

**Comment by orestesgaolin** [comment]
jsonEncode was expecting toJson and we used toMap, will issue new PR for that soon

**Comment by Nash0x7E2** [comment]
Ok cool!

**Comment by Nash0x7E2** [comment]
Nice, I’ll use a temp work around on my branch until it lands.
