### ISSUE TITLE
Audio playback on Android

### ISSUE THREAD

**Issue by tomisparker** [juntofoundation/junto-mobile#811]
The length of an audio expression is not showing up, just zeros across the board and when you press play the circle moves all the way across the line within a second and shows zeros on the time and then begins playing the expression from there

**Comment by orestesgaolin** [comment]
Thanks I hope to fix this after the Cognito stuff

**Comment by Nash0x7E2** [comment]
@orestesgaolin I was looking at this crash yesterday/today. The crash seems to be coming from within the plugin. There are times while testing where audio playback works completely fine and other time where the duration comes back as null or 0

**Comment by Nash0x7E2** [comment]
Crash Log:

```bash
E/flutter (32475): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(Unexpected error!, Attempt to invoke virtual method 'int android.media.MediaPlayer.getDuration()' on a null object reference, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getDuration()' on a null object reference
E/flutter (32475): 	at xyz.luan.audioplayers.WrappedMediaPlayer.getDuration(WrappedMediaPlayer.java:148)
E/flutter (32475): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:110)
E/flutter (32475): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/flutter (32475): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/flutter (32475): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (32475): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:650)
E/flutter (32475): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (32475): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (32475): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (32475): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter (32475): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32475): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (32475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (32475): )
E/flutter (32475): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (32475): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (32475): <asynchronous suspension>
E/flutter (32475): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (32475): #3      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:319:10)
E/flutter (32475): #4      AudioPlayer.getDuration (package:audioplayers/audioplayers.dart:528:12)
E/flutter (32475): #5      AudioService._getDuration (package:junto_beta_mobile/screens/create/create_templates/audio_service.dart:124:41)
E/flutter (32475): #6      AudioService.playRecording.<anonymous closure> (package:junto_beta_mobile/screens/create/create_templates/audio_service.dart:116:9)
E/flutter (32475): #7      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (32475): #8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32475): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32475): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (32475): #11     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (32475): #12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (32475): #13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (32475): #14     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (32475): #15     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (32475): #16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (32475): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (32475): #18     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (32475): #19     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (32475): #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (32475): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (32475): #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (32475): #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

I am so going to create an issue for this in the package repo https://github.com/luanpotter/audioplayers since this crash occurs inside the plugin. iOS implementation and playback seem fine.

**Comment by sunyatax** [comment]
@fayeed Maybe you can see if you can resolve this one

**Comment by fayeed** [comment]
@sunyatax Was able to get rid of the error mentioned in this issue but another error pops up after the audio player finishes playing audio, I suppose the package is a little too buggy, there are a lot of issues already opened for these errors, I think we should look at other packages.

**Comment by sunyatax** [comment]
Okay, can you take a look at some other packages and see if there's a better solution? @fayeed
