### ISSUE TITLE
Audio expression preview overflows 

### ISSUE THREAD

**Issue by Nash0x7E2** [juntofoundation/junto-mobile#824]
```
I/flutter (30865): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30865): The following assertion was thrown building Consumer<AudioService>(dirty, dependencies:
I/flutter (30865): [_DefaultInheritedProviderScope<AudioService>]):
I/flutter (30865): 'package:flutter/src/material/slider.dart': Failed assertion: line 171 pos 15: 'min <= max': is not
I/flutter (30865): true.
I/flutter (30865): 
I/flutter (30865): The relevant error-causing widget was:
I/flutter (30865):   Consumer<AudioService>
I/flutter (30865):   file:///Users/nash/git_projects/junto_mobile/lib/widgets/audio/audio_seek.dart:15:12
I/flutter (30865): 
I/flutter (30865): When the exception was thrown, this was the stack:
I/flutter (30865): #2      new Slider (package:flutter/src/material/slider.dart:171:15)
I/flutter (30865): #3      AudioSeek.build.<anonymous closure> (package:junto_beta_mobile/widgets/audio/audio_seek.dart:33:22)
I/flutter (30865): #4      Consumer.buildWithChild (package:provider/src/consumer.dart:175:19)
I/flutter (30865): #5      SingleChildStatelessWidget.build (package:nested/nested.dart:260:41)
I/flutter (30865): #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4585:28)
I/flutter (30865): #7      SingleChildStatelessElement.build (package:nested/nested.dart:280:18)
I/flutter (30865): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4511:15)
I/flutter (30865): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
I/flutter (30865): #10     StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
I/flutter (30865): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
I/flutter (30865): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
I/flutter (30865): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
I/flutter (30865): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5531:32)
I/flutter (30865): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5966:17)
I/flutter (30865): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
I/flutter (30865): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
I/flutter (30865): #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
I/flutter (30865): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
I/flutter (30865): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
I/flutter (30865): #25     StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
I/flutter (30865): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
I/flutter (30865): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
I/flutter (30865): #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
I/flutter (30865): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
I/flutter (30865): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
I/flutter (30865): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
I/flutter (30865): #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4871:5)
I/flutter (30865): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #37     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5531:32)
I/flutter (30865): #38     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5966:17)
I/flutter (30865): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #40     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5531:32)
I/flutter (30865): #41     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5966:17)
I/flutter (30865): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
I/flutter (30865): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
I/flutter (30865): #45     StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
I/flutter (30865): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
I/flutter (30865): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
I/flutter (30865): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
I/flutter (30865): #49     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2632:33)
I/flutter (30865): #50     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
I/flutter (30865): #51     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (30865): #52     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (30865): #53     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (30865): #54     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (30865): #58     _invoke (dart:ui/hooks.dart:267:10)
I/flutter (30865): #59     _drawFrame (dart:ui/hooks.dart:225:3)
I/flutter (30865): (elided 5 frames from class _AssertionError and dart:async)
I/flutter (30865): 
I/flutter (30865): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (30865): Another exception was thrown: A RenderFlex overflowed by 99731 pixels on the right.
```

**Comment by orestesgaolin** [comment]
I may try to fix audio issues after the cognito task

**Comment by Nash0x7E2** [comment]
I am working on this now lol

**Comment by sunyatax** [comment]
Is this still an issue? @Nash0x7E2 @orestesgaolin
