### ISSUE TITLE
Login is broken on latest dev

### ISSUE THREAD

**Issue by Nash0x7E2** [juntofoundation/junto-mobile#838]
When trying to log in on the latest dev, the following error is thrown. 

```
Error during user login
I/flutter ( 4661): type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
I/flutter ( 4661): #0      AuthenticationServiceCentralized.loginUser (package:junto_beta_mobile/backend/services/auth_service.dart:37:23)
I/flutter ( 4661): <asynchronous suspension>
I/flutter ( 4661): #1      AuthRepo.loginUser (package:junto_beta_mobile/backend/repositories/auth_repo.dart:98:48)
I/flutter ( 4661): #2      AuthBloc._mapLoginEventState (package:junto_beta_mobile/screens/welcome/bloc/auth_bloc.dart:87:35)
I/flutter ( 4661): <asynchronous suspension>
I/flutter ( 4661): #3      AuthBloc.mapEventToState (package:junto_beta_mobile/screens/welcome/bloc/auth_bloc.dart:43:14)
I/flutter ( 4661): <asynchronous suspension>
I/flutter ( 4661): #4      Bloc._bindEventsToStates.<anonymous closure> (package:bloc/src/bloc.dart:252:20)
I/flutter ( 4661): #5      Stream.asyncExpand.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:573:30)
I/flutter ( 4661): #6      _rootRunUnary (dart:async/zone.dart:1206:13)
I/flutter ( 4661): #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter ( 4661): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter ( 4661): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
I/flutter ( 4661): #10     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
I/flutter ( 4661): #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
I/flutter ( 4661): #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
I/flutter ( 4661): #13     _rootRun (dart:async/zone.dart:1182:47)
I/flutter ( 4661): #14     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 4661): #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter ( 4661): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
I/flutter ( 4661): #17     _rootRun (dart:async/zone.dart:1190:13)
I/flutter ( 4661): #18     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 4661): #19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter ( 4661): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
I/flutter ( 4661): #21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
I/flutter ( 4661): #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter ( 4661): 
I/flutter ( 4661): [ERROR] [PrintLogger.logException]: Caught error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
I/flutter ( 4661): [DEBUG] [PrintLogger.logException]: In dev mode. Not sending report to Sentry.io.
I/flutter ( 4661): type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
I/flutter ( 4661): [ERROR] [PrintLogger.logException]: Caught error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
I/flutter ( 4661): [DEBUG] [PrintLogger.logException]: In dev mode. Not sending report to Sentry.io.
```

**Comment by orestesgaolin** [comment]
Seems like @jdeepee deployed the new version

**Comment by Nash0x7E2** [comment]
Might be, the `created_at` date is not being parsed properly.

**Comment by orestesgaolin** [comment]
I think this might be closed after latest change to cognito
